spring.application.name=box-delivery-service
spring.config.import=optional:file:.env[.properties]

#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.dependencies.depends-on=flyaway
spring.flyway.locations=classpath:db/migration

spring.jackson.date-format=dd-MM-yyyy

logging.level.com.box_delivery=INFO
spring.jpa.show-sql=false

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASS}
#spring.datasource.password=0sghXCUWxaLcemIo

#spring.datasource.url=jdbc:postgresql://localhost:5432/car-mgmt?sslmode=disable
#spring.datasource.username=postgres
#spring.datasource.password=password


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
